runtime: python37


handlers:
  - url: /static
    static_dir: static

  - url: /static/favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /.*
    script: auto


env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://root:password@/mydatabase?unix_socket=/cloudsql/smart-recipes-cc:australia-southeast1:mydatabase
    # DIALOGFLOW_PROJECT_ID: smart-recipes-cc 
    # GOOGLE_APPLICATION_CREDENTIALS: 'smart-recipes-cc-f19370999494.json'
    CLOUD_STORAGE_BUCKET: recipes-pic


# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: smart-recipes-cc:australia-southeast1:mydatabase